work_dir: gcn/small_dataset
#pretrained_weights: ./model/st_gcn.kinetics.pt
#pretrained_weights: ./triplet/best_model.pt

feeder: feeder.feeder.Feeder
train_feeder_args:
  normalization: False
  random_choose: True
  random_move: True
  random_shift: False
  window_size: 25
  relabel: True
  data_path: ./data/small/train_data_small.npy
  label_path: ./data/small/train_label_small.pkl
gallery_feeder_args:
  relabel: False
  data_path: ./data/small/gallery_data_small.npy
  label_path: ./data/small/gallery_label_small.pkl
probe_feeder_args:
  relabel: False
  data_path: ./data/small/probe_data_small.npy
  label_path: ./data/small/probe_label_small.pkl

#model
model: net.st_gcn.Model
model_args:
  in_channels: 4
  num_class: 50
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'cvid_reid'
    strategy: 'spatial'

#optim
#weight_decay: 0.0001
base_lr: 0.08
step: [50, 100]

# training
device: [0]
batch_size: 128
test_batch_size: 1
num_epoch: 200